### PR TITLE
MB-Lab: Automatic lip-sync feature

### PR DESCRIPTION
**Pull request by amirpavlo**
This currently only works for linux.

This feature enables the user to add a .wav file and .txt transcript
of the audio file. It then marks the wav file with phonemes. Then
it can automatically create a lipsync or it can create a lip-sync
one phoneme at a time

Signed-off-by: Amir Shehata <amir.shehata@gmail.com>

### CODE REVIEW

**Comment by animate1978** [comment]
I've thought about this and I am not so sure I want to add external dependencies to MB-Lab, at least not right now? I will keep this open for now as we can discuss this. I am on my Windows install right now, updating Blender and testing on it so I will be able to test this new code in the next few days. Not wholly rejecting this pull request, just want to get more info before we commit something

**Comment by amirpavlo** [comment]
sure. What info do you want? We can't get around the 3rd party dependency at this point, since the speech parser depends on pocketsphinx. Even blender-rhubarb-lip-sync which sort of does the same thing, depends on rhubarb-lip-sync which in turn depends on pocketsphinx. What that blender add-on did is to allow the user to specify the binary/executable of rhubarb-lip-sync. What I did is I packaged the libraries needed for speech parsing and I dynamically load them in the addon, then call them from python. This is the approach taken by add-ons like FLIP-FLUID for example. I think that approach makes more sense and it's more user friendly, since it avoids the user having to go and grab the dependencies manually.

The other option I could take, is I can break this out in its own blender-add-on, which TBH, I was thinking of doing anyway, because I wanted to adapt it for makehuman. The good thing about having it integrated it with MB-Lab though, is it'll just be a few clicks away. The user doesn't really need to do much else to get it working.

Anyway, let me know what you think.

**Comment by NumesSanguis** [comment]
Thank you for your effort @amirpavlo ! I tried to install this pull request as MB-Lab.zip, but I got the following error:

    Read prefs: /home/*user*/.config/blender/2.80/config/userpref.blend
    found bundled python: /home/*user*/Downloads/blender-2.80-a070815d127e-linux-glibc224-x86_64/2.80/python
    addon_utils.disable: MB-Lab-master not disabled
    Modules Installed (MB-Lab-master) from '/home/*user*/Downloads/MB-Lab-1-7-3-lip-sync.zip' into '/home/*user*/.config/blender/2.80/scripts/addons'
    /home/*user*/.config/blender/2.80/scripts/addons/MB-Lab-master/yasp/sphinxinstall/lib/libsphinxbase.so: file too short
    Failed to load libraries
    mb_lab updater verbose is enabled
    cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_install_popup'>
    cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_install_popup'>
    cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_check_now'>
    cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_check_now'>
    cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_update_now'>
    cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_update_now'>
    cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_update_target'>
    cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_update_target'>
    cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_install_manually'>
    cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_install_manually'>
    cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_updated_successful'>
    cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_updated_successful'>
    cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_restore_backup'>
    cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_restore_backup'>
    cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_ignore'>
    cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_ignore'>
    cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_end_background'>
    cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_end_background'>
    mb_lab: Wrote out updater json settings to file, with the contents:
    {'last_check': '', 'backup_date': '', 'update_ready': False, 'ignore': False, 'just_restored': False, 'just_updated': False, 'version_text': {}}

# System
- Ubuntu 16.04
- Blender 2.8 (latest build, downloaded today, `blender-2.80-a070815d127e-linux-glibc224-x86_64`)
- MB-Lab version: Your master branch (https://github.com/amirpavlo/MB-Lab/)

# Discussion on including external libraries
Please see the full length discussion on the Discord channel #face-lip-sync (https://discordapp.com/invite/FuJGcVN)

Summary (my opinion): Including external dependencies for features not intended for all users of this add-on will make this a very convoluted project in the long-run, when more people want their useful tools added. Therefore, I suggest we should find a modular approach that keep this code base as slim as possible, but allows for easy additions.

**Comment by animate1978** [comment]
I am going to have to agree.

As awesome as this code addition is, relying on external dependencies will require quite a bit of effort in addition to what is already a complex project. Upon researching how to compile for Windows it would require quite a bit of user setup that most would just not prefer. There was mention of an installer for the pocketsphinx Windows build, however that again adds another layer of issues specific to Windows. I also do not have a Mac system so I cannot test against that OS either so that leaves Mac users out in the cold in terms of support and development.

I did think about making a new branch just for this additional code but maintaining this again would add more complexity since this would require two versions of MB-Lab that only one has a large list of requirements versus strictly Python code.

There has been much discussion regarding this across many channels so this decision to deny the merge does not come lightly.

Hopefully you can continue to build this amazing code into a modular addon that would be compatible with MB-Lab in such a way like Rigify for MB-Lab addon is.

We do encourage more development from you though so please don't think of this as a rejection entirely, it just comes down to what time and resources we all have available to commit to this project.

**Pull request closed without merging**
