### PR TITLE
MB-Lab: Face Rig and assets

### PR DESCRIPTION
**Pull request by amirpavlo**
Added a Face Rig to drive the expression shapekeys

Added a set of assets which can be used with the human models

Signed-off-by: Amir Shehata <amir.shehata@gmail.com>

### CODE REVIEW

**Comment by amirpavlo** [comment]
I changed the humanoid_library.blend file. So if you've made changes to that, there could be a conflict there. Best bet is to append the face_rig collection to your own humanoid_library.blend file, to avoid losing any changes you might've made to that file.

For the assets they should all have the textures embedded in the blend file, that's why they are larger files. I did try to use git lfs, but github doesn't have complete integration with it. Basically it works if you clone the repo. But if someone tries to download the .zip file, then it won't include the assets which are git lfs tracked. I'm now thinking to have a separate place where people can download assets ready to work with MB-Lab. Not sure the best way though. Makehuman has this community repository which you can hook to after you install makehuman.

**Comment by amirpavlo** [comment]
Ok I used the MB-Lab humanoid_library.blend and appended the face_rig, so it should be no problem merging with the existing branch.

**Comment by animate1978** [comment]
Very nice! I was at work and merged your commit through my phone so I was not able to play with this until now. I am liking this! Very well done!

**Comment by amirpavlo** [comment]
Thank you sir. The next project I'll work on is making a lip-syncing rig. There are ways to do it right now, but I'm not sure I'm a fan yet. I'm doing some research to see how I can use an open source Automatic Speech Recognition engine to analyze an audio clip and generate data which can be used to create first pass lip-syncing animation.

By the way looks like Manuel Bastioni removed his website and all documentation. Luckily, I predicted this move once he started removing his youtube channel, so I downloaded his entire site. We wouldn't be breaking any rules to create our own wiki based on that, would we? I think documentation is key for new users to start using the lab.

**Comment by animate1978** [comment]
Yes his site is now gone too. I am planning on setting up a new website for this addon, as you mentioned docs are important. I think that using Manuel's site wouldn't technically be breaking rules, he did license the imagery as CC-BY (or CC0) for instance so we can still use them, we would just have to edit the docs to be current with the addon now that a LOT of updates have happened. Not sure if I should use Github's Pages for that or go and set up a domain and get a web host. Either option is good.

**Pull request merged**
