### PR TITLE
Ported ManuelBastioni lab to blender 2.8

### PR DESCRIPTION
**Pull request by amirpavlo**
First take at porting to Blender 2.8
Preliminary testing shows similar behaviour to 2.79
Suggest to keep it on separate branch.
Signed-off-by: Amir Shehata <amir.shehata@gmail.com>

### CODE REVIEW

**Comment by animate1978** [comment]
Nice! I just created a Blender 2.80 branch on my repo so whenever you are ready

**Comment by amirpavlo** [comment]
Looks like you already grabbed it. Cool.
One thing I have on my wish list is to create a facial rig for the lab characters, similar to makehuman. The face shape keys are good, but I think having a facial rig can provide more flexibility. Do you have hints on where to start with that?

**Comment by animate1978** [comment]
There is the Rigify MB-Lab addon here https://github.com/danielenger/Rigify-Meta-Rig-for-MB-Lab

Personally I am not good at rigging myself, I have yet to really test this script above but from what I see is that it builds a face rig for the MB-Lab character.

**Comment by amirpavlo** [comment]
I looked through this script. I don't think it creates a face rig. As far as I understand this script, it takes all the existing MB bones and translates them into rigify bones, renaming the vertex groups. Since there are no face bones in the MB armature, it doesn't do anything special with it. I played around with it briefly but I couldn't get it to work yet. I'm probably missing some step there. 

What I'm trying to do now is to create a rig to drive the shape keys already in existence. I'll then try to script it, so they can be generated automatically by the add-on. I think that'll be useful for general use.

Also note, when I tested the community version of the lab, the materials don't seem to work very well with EEVEE. The materials from 1.6.1a seem to work better. Need to enable the "Screen Space Reflections" in EEVEE, however. I ported the lab based on 1.6.1a to keep a live copy of it on my github. I'm planning to make my changes for both the community version and this one.

I started an initiative to create some clothing assets for the Lab as well. But the blend files are larger since I pack the textures. For my local 1.6.1a based repo I enable git lfs. If you do the same for yours, I can add the clothing assets there as well.

**Comment by animate1978** [comment]
Honestly EEVEE runs real slow on my system I am developing MB-Lab on, it crashes X constantly. I am currently in the process of converting another system to a windows system because of more video card issues, I want to work on some Unreal stuff related to MB-Lab but it runs horribly on said workstation... Should have a working development environment for MB-Lab and Unreal done by this weekend.

As for the face rig I say go for it, I have not had success with Rigify much as I keep getting bugs, not sure what that is about, so if you can develop a facial rig that works I think would be a nice update.

I have to read up on git lfs, haven't used it before.

**Comment by amirpavlo** [comment]
https://git-lfs.github.com/

**Pull request closed without merging**
